name: Deploy Build via FTP
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: npm i --force && npm run build
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
      - name: Deploy build over FTP
        env:
          FTP_HOST: hajonsoft.net
          FTP_USER: ftp@hajonsoft.net
          FTP_PASS: ${{ secrets.SITEGROUND_FTP_PASSWORD }}
          FTP_REMOTE_DIR: /public_html/
          FTP_LOCAL_DIR: ./build/
        run: |
          lftp -e "
          set ftp:passive-mode true;
          set ftp:ssl-allow true;
          set ssl:verify-certificate no;
          open -u $FTP_USER,$FTP_PASS $FTP_HOST;
          mirror -R --delete --verbose $FTP_LOCAL_DIR $FTP_REMOTE_DIR;
          bye
          "
